# Generated by Django 4.2.2 on 2023-07-12 10:14

from django.db import migrations, models

# DAMN! IF I CREATE MY OWN MIGRATION, IT STILL ROLLS BACK TO THE PREVIOUS
# CONFIGURATIONS


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_blog_post_published_on_80a593_idx_blog_post_publish_80a593_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_published_on_80a593_idx",
            old_name="blog_post_publish_80a593_idx",
        ),
    ]
