# Generated by Django 4.2.2 on 2023-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_custom"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_publish_80a593_idx",
            old_name="blog_post_published_on_80a593_idx",
        ),
    ]
